

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */
public class AdminScreen extends javax.swing.JFrame {
    DefaultTableModel model;
    Connection conn;
    PreparedStatement ps; 
    int upempid,fin,fin2;
    String updateempid;
    String updateroom1;
        
    /**
     * Creates new form AdminScreen
     */
    String gender1;
    public AdminScreen() {
        initComponents();
        this.setPreferredSize(new Dimension(1500, 1500));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        groupRadio();
        
        
    }
    public void groupRadio(){
        
        genderGroup.add(MaleRadio);
        genderGroup.add(FemaleRadio);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Emp_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Emp_DOB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Emp_Address = new javax.swing.JTextField();
        Emp_Aadhar = new javax.swing.JTextField();
        Emp_Pass = new javax.swing.JTextField();
        MaleRadio = new javax.swing.JRadioButton();
        FemaleRadio = new javax.swing.JRadioButton();
        Emp_Salary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEmployee = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmployeeUpdate = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Room_Type = new javax.swing.JTextField();
        Room_No = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        upfield = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        roomtable = new javax.swing.JTable();
        Room_Rate = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        uproomno = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        uproom = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        custtable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        newname = new javax.swing.JTextField();
        newdob = new javax.swing.JTextField();
        newaddress = new javax.swing.JTextField();
        newdoj = new javax.swing.JTextField();
        newaadhar = new javax.swing.JTextField();
        newgender = new javax.swing.JTextField();
        newpassword = new javax.swing.JTextField();
        newsalary = new javax.swing.JTextField();
        newroomno = new javax.swing.JTextField();
        newstatus = new javax.swing.JTextField();
        newtype = new javax.swing.JTextField();
        newrate = new javax.swing.JTextField();
        emppush = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Emp_DOJ = new javax.swing.JTextField();
        newid = new javax.swing.JTextField();
        Room_Status = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Emp_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_NameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel3.setText("DATE OF BIRTH");

        Emp_DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_DOBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel4.setText("ADDRESS");

        jLabel6.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel6.setText("AADHAR NUMBER");

        jLabel7.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel7.setText("GENDER");

        jLabel8.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel8.setText("SALARY");

        jLabel9.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel9.setText("PASSWORD");

        Emp_Aadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_AadharActionPerformed(evt);
            }
        });

        Emp_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_PassActionPerformed(evt);
            }
        });

        genderGroup.add(MaleRadio);
        MaleRadio.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        MaleRadio.setText("MALE");
        MaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioActionPerformed(evt);
            }
        });

        genderGroup.add(FemaleRadio);
        FemaleRadio.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        FemaleRadio.setText("FEMALE");
        FemaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\om\\Pictures\\Screenshots\\Screenshot (64).png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel2.setText(" NAME");

        TableEmployee.setBorder(new javax.swing.border.MatteBorder(null));
        TableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "DOB", "DOJ", "ADDRESS", "AADHAR", "GENDER", "PASSWORD", "SALARY"
            }
        ));
        jScrollPane1.setViewportView(TableEmployee);

        jButton2.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton2.setText("VIEW EMPLOYEES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton3.setText("ADD EMPLOYEE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton4.setText("REMOVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        EmployeeUpdate.setBorder(new javax.swing.border.MatteBorder(null));
        EmployeeUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "DOB", "DOJ", "ADDRESS", "AADHAR", "GENDER", "PASSWORD", "SALARY"
            }
        ));
        jScrollPane2.setViewportView(EmployeeUpdate);

        jLabel20.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        jLabel20.setText("EMPLOYEE");

        jLabel13.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel13.setText("ROOM NO.");

        jLabel14.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel14.setText("TYPE");

        Room_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_TypeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton1.setText("GO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel10.setText("UPDATE EMPLOYEE");

        jLabel11.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel11.setText("EMPLOYEE ID");

        upfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upfieldActionPerformed(evt);
            }
        });

        roomtable.setBorder(new javax.swing.border.MatteBorder(null));
        roomtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ROOM NO.", "TYPE", "STATUS", "RATE"
            }
        ));
        jScrollPane3.setViewportView(roomtable);

        Room_Rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_RateActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton6.setText("VIEW ROOMS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel15.setText("RATE");

        jButton5.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton5.setText("ADD ROOM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        uproomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uproomnoActionPerformed(evt);
            }
        });

        uproom.setBorder(new javax.swing.border.MatteBorder(null));
        uproom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ROOM NO.", "TYPE", "STATUS", "RATE"
            }
        ));
        uproom.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                uproomAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(uproom);

        jLabel17.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        jLabel17.setText("CUSTOMERS");

        jButton11.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton11.setText("VIEW CUSTOMERS");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        custtable.setBorder(new javax.swing.border.MatteBorder(null));
        custtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FNAME", "MNAME", "LNAME", "AADHAR", "PH. PRI", "PH. SEC", "EMAIL", "ADDRESS", "GENDER", "MARRIAGE", "DOB"
            }
        ));
        jScrollPane5.setViewportView(custtable);

        jLabel16.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel16.setText("UPDATE ROOM");

        jButton9.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton9.setText("GO");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton10.setText("REMOVE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel18.setText("ROOM NO.");

        jButton12.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton12.setText("LOG OUT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        jLabel21.setText("ROOMS");

        emppush.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        emppush.setText("PUSH");
        emppush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emppushActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton8.setText("PUSH");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel12.setText("DATE OF JOINING");

        Emp_DOJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_DOJActionPerformed(evt);
            }
        });

        Room_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_StatusActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jLabel19.setText("STATUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(511, 511, 511))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(538, 538, 538))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(500, 500, 500))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(526, 526, 526))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emppush)
                            .addComponent(jLabel21))
                        .addGap(531, 531, 531))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(newroomno, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newtype, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newrate))
                            .addComponent(jButton12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(348, 348, 348)
                                    .addComponent(jLabel18)
                                    .addGap(18, 18, 18)
                                    .addComponent(uproomno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton10))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(329, 329, 329)
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(upfield, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(441, 441, 441)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(439, 439, 439)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(newid, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newdob)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newdoj, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(398, 398, 398)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel19))
                                                .addGap(108, 108, 108)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Room_Rate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Room_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Room_No, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Room_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)))
                                        .addComponent(newgender, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(newsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(536, 536, 536))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(491, 491, 491))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(514, 514, 514))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(74, 74, 74)
                                .addComponent(Emp_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(88, 88, 88)
                                .addComponent(Emp_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(93, 93, 93)
                                .addComponent(MaleRadio)
                                .addGap(135, 135, 135)
                                .addComponent(FemaleRadio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(23, 23, 23)
                                .addComponent(Emp_Aadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(98, 98, 98)
                                .addComponent(Emp_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel12))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Emp_DOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(Emp_DOJ, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Emp_Name)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(jLabel20)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(Emp_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emp_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emp_DOJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Emp_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(MaleRadio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(FemaleRadio)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel6))
                            .addComponent(Emp_Aadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(Emp_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel9))
                            .addComponent(Emp_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jButton3)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel10)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addComponent(upfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newdoj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(emppush, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room_Rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uproomno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newroomno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(42, 42, 42)
                .addComponent(jButton11)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton12)
                .addGap(24, 24, 24))
        );

        jScrollPane6.setViewportView(jPanel1);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(20, 20, 1120, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateempid = this.upfield.getText();
        upempid=Integer.parseInt(updateempid);
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAME");
        model.addColumn("DOB");
        model.addColumn("DOJ");
        model.addColumn("ADDRESS");
        model.addColumn("AADHAR");
        model.addColumn("GENDER");
        model.addColumn("PASSWORD");
        model.addColumn("SALARY");
        
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from Employee where Emp_ID= ? ");
            ps.setString(1, updateempid);
            ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Emp_ID"), rs.getString("Emp_Name"), rs.getString("Emp_DOB"), rs.getString("Emp_DOJ"), rs.getString("Emp_Address"), rs.getString("Emp_Aadhar"), rs.getString("Emp_Gender"), rs.getString("Emp_Pass"), rs.getString("Emp_Salary")});
                }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        EmployeeUpdate.setModel(model);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FemaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioActionPerformed
        // TODO add your handling code here:
        gender1= FemaleRadio.getText();
    }//GEN-LAST:event_FemaleRadioActionPerformed

    private void Emp_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emp_NameActionPerformed

    private void Emp_DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emp_DOBActionPerformed

    private void Emp_AadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_AadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emp_AadharActionPerformed

    private void Emp_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emp_PassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAME");
        model.addColumn("DOB");
        model.addColumn("DOJ");
        model.addColumn("ADDRESS");
        model.addColumn("AADHAR");
        model.addColumn("GENDER");
        model.addColumn("PASSWORD");
        model.addColumn("SALARY");
        
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from Employee");
            ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Emp_ID"), rs.getString("Emp_Name"), rs.getString("Emp_DOB"), rs.getString("Emp_DOJ"), rs.getString("Emp_Address"), rs.getString("Emp_Aadhar"), rs.getString("Emp_Gender"), rs.getString("Emp_Pass"), rs.getString("Emp_Salary")});
                }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        TableEmployee.setModel(model);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name;
        name = this.Emp_Name.getText();
        String dob;
        dob = this.Emp_DOB.getText();
        String doj;
        doj = this.Emp_DOJ.getText();
        String address;
        address = this.Emp_Address.getText();
        String aadhar;
        aadhar = this.Emp_Aadhar.getText();
        String salary;
        salary = this.Emp_Salary.getText();
        String password;
        password = this.Emp_Pass.getText();
        try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
                    ps = conn.prepareStatement("insert into Employee (Emp_Name,Emp_DOB,Emp_DOJ,Emp_Address,Emp_Aadhar,Emp_Salary,Emp_Pass,Emp_Gender) values(?,?,?,?,?,?,?,?)");
                    ps.setString(1, name);
                    ps.setString(2, dob);
                    ps.setString(3, doj);
                    ps.setString(4, address);
                    ps.setString(5, aadhar);
                    ps.setString(6, salary);
                    ps.setString(7, password);
                    ps.setString(8, gender1);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Employee Record Added");
                    AdminScreen as = new AdminScreen();
            as.setVisible(true);
            as.setLocationRelativeTo(null);
            this.dispose();
                }   
                catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Fill All The Details");
            
        }
        
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void upfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upfieldActionPerformed
        // TODO add your handling code here:
        String temp=upfield.getText();
        fin = Integer.parseInt(temp);
    }//GEN-LAST:event_upfieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try {
            
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("delete from Employee where Emp_ID=?");
            ps.setString(1, updateempid);
           
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String number;
        number = this.Room_No.getText();
        String type;
        type = this.Room_Type.getText();
        String rate;
        rate = this.Room_Rate.getText();
        String status;
        status = this.Room_Status.getText();
        try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
                    ps = conn.prepareStatement("insert into Rooms (Room_No,Room_Type,Room_Rate,Room_Status) values(?,?,?,?)");
                    ps.setString(1, number);
                    ps.setString(2, type);
                    ps.setString(3, rate);
                    ps.setString(4, status);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Room Record Added");
                    AdminScreen as = new AdminScreen();
            as.setVisible(true);
            as.setLocationRelativeTo(null);
            this.dispose();
                }   
                catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Fill All The Details");
            
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        model = new DefaultTableModel();
        model.addColumn("ROOM NO.");
        model.addColumn("TYPE");
        model.addColumn("STATUS");
        model.addColumn("RATE");
        
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from Rooms");
            ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Room_No"), rs.getString("Room_Type"), rs.getString("Room_Status"), rs.getString("Room_Rate")});
                }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        roomtable.setModel(model);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Room_RateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_RateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_RateActionPerformed

    private void Room_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_TypeActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String updateroom = this.uproomno.getText();
        updateroom1=updateroom;
        model = new DefaultTableModel();
        model.addColumn("ROOM NO.");
        model.addColumn("TYPE");
        model.addColumn("STATUS");
        model.addColumn("RATE");
        
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from Rooms where Room_No=?");
            ps.setString(1, updateroom);
            ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Room_No"), rs.getString("Room_Type"), rs.getString("Room_Status"), rs.getString("Room_Rate")});
                }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        uproom.setModel(model);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try {
            
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("delete from Rooms where Room_No=?");
            ps.setString(1, updateroom1);
           
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Room Deleted Successfully!");
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void uproomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uproomnoActionPerformed
        // TODO add your handling code here:
        String temp=uproomno.getText();
        fin2 = Integer.parseInt(temp);
    }//GEN-LAST:event_uproomnoActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("FNAME");
        model.addColumn("MNAME");
        model.addColumn("LNAME");
        model.addColumn("AADHAR");
        model.addColumn("PH. PRI");
        model.addColumn("PH. SEC");
        model.addColumn("EMAIL");
        model.addColumn("ADDRESS");
        model.addColumn("GENDER");
        model.addColumn("MARRIAGE");
        model.addColumn("DOB");
           
        
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from Customer");
            ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Cust_ID"),rs.getString("Cust_Fname"),rs.getString("Cust_Mname"),rs.getString("Cust_Lname"),rs.getString("Cust_Aadhar"),rs.getString("Cust_Ph_Primary"),rs.getString("Cust_Ph_Secondary"),rs.getString("Cust_Email"),rs.getString("Cust_Address"),rs.getString("Cust_Gender"),rs.getString("Cust_Marriage"),rs.getString("Cust_DOB"), });
                }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        custtable.setModel(model);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Admin a = new Admin();
            a.setVisible(true);
            a.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void emppushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emppushActionPerformed
        // TODO add your handling code here:
        String id;
        id=this.newid.getText();
        String name1;
        name1 = this.newname.getText();
        String dob1;
        dob1 = this.newdob.getText();
        String doj1;
        doj1 = this.newdoj.getText();
        String address1;
        address1 = this.newaddress.getText();
        String aadhar1;
        aadhar1 = this.newaadhar.getText();
        String gender2;
        gender2 = this.newgender.getText();
        String password1;
        password1 = this.newgender.getText();
        String salary1;
        salary1 = this.newsalary.getText();
        
        try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
                    ps = conn.prepareStatement("update Employee set Emp_ID=?, Emp_Name=?, Emp_DOB=?,Emp_DOJ=?,Emp_Address=?,Emp_Aadhar=?,Emp_Gender=?,Emp_Pass=?,Emp_Salary=? where Emp_ID=?");
                    ps.setString(1, id);
                    ps.setString(2, name1);
                    ps.setString(3, dob1);
                    ps.setString(4, doj1);
                    ps.setString(5, address1);
                    ps.setString(6, aadhar1);
                    ps.setString(7, gender2);
                    ps.setString(8, password1);
                    ps.setString(9, salary1);
                    ps.setInt(10, fin);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Employee Record Updated!");
                    AdminScreen as = new AdminScreen();
            as.setVisible(true);
            as.setLocationRelativeTo(null);
            this.dispose();
                }   
                catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Fill All The Details");
            
        }
    }//GEN-LAST:event_emppushActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String number = newroomno.getText();
        String type = newtype.getText();
        String status = newstatus.getText();
        String rate = newrate.getText();
        
        try {

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("update Rooms set Room_No=?, Room_Type=?, Room_Status=?, Room_Rate=? where Room_No = ? ");
            ps.setString(1, number);
            ps.setString(2, type);
            ps.setString(3, status);
            ps.setString(4, rate);
            ps.setInt(5, fin2);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            
        }     
        catch (SQLException ex) {
            Logger.getLogger(AdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void Emp_DOJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_DOJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emp_DOJActionPerformed

    private void MaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioActionPerformed
        // TODO add your handling code here:
        gender1= MaleRadio.getText();
    }//GEN-LAST:event_MaleRadioActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void uproomAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_uproomAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_uproomAncestorAdded

    private void Room_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_StatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emp_Aadhar;
    private javax.swing.JTextField Emp_Address;
    private javax.swing.JTextField Emp_DOB;
    private javax.swing.JTextField Emp_DOJ;
    private javax.swing.JTextField Emp_Name;
    private javax.swing.JTextField Emp_Pass;
    private javax.swing.JTextField Emp_Salary;
    private javax.swing.JTable EmployeeUpdate;
    private javax.swing.JRadioButton FemaleRadio;
    private javax.swing.JRadioButton MaleRadio;
    private javax.swing.JTextField Room_No;
    private javax.swing.JTextField Room_Rate;
    private javax.swing.JTextField Room_Status;
    private javax.swing.JTextField Room_Type;
    private javax.swing.JTable TableEmployee;
    private javax.swing.JTable custtable;
    private javax.swing.JButton emppush;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField newaadhar;
    private javax.swing.JTextField newaddress;
    private javax.swing.JTextField newdob;
    private javax.swing.JTextField newdoj;
    private javax.swing.JTextField newgender;
    private javax.swing.JTextField newid;
    private javax.swing.JTextField newname;
    private javax.swing.JTextField newpassword;
    private javax.swing.JTextField newrate;
    private javax.swing.JTextField newroomno;
    private javax.swing.JTextField newsalary;
    private javax.swing.JTextField newstatus;
    private javax.swing.JTextField newtype;
    private javax.swing.JTable roomtable;
    private javax.swing.JTextField upfield;
    private javax.swing.JTable uproom;
    private javax.swing.JTextField uproomno;
    // End of variables declaration//GEN-END:variables
}
