/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar(TEST)
 */
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CustomerEntry extends javax.swing.JFrame {
     Connection conn;
    PreparedStatement ps; 
    /**
     * Creates new form Login
     */
    public CustomerEntry() {
        initComponents();
        this.setPreferredSize(new Dimension(1500, 1500));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Label_Logo_CE = new javax.swing.JLabel();
        TextField_Ph_Pri_CE = new javax.swing.JTextField();
        Label_Ph_Pri_CE = new javax.swing.JLabel();
        Button_Register_CE = new javax.swing.JButton();
        Label_CustEntry_CE = new javax.swing.JLabel();
        Button_Back_CE = new javax.swing.JButton();
        Button_Login_CE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Label_Logo_CE.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_CE.setIcon(new javax.swing.ImageIcon("C:\\Users\\om\\Pictures\\Screenshots\\Screenshot (64).png")); // NOI18N

        TextField_Ph_Pri_CE.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        TextField_Ph_Pri_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Ph_Pri_CEActionPerformed(evt);
            }
        });

        Label_Ph_Pri_CE.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Ph_Pri_CE.setText("PHONE NO.(PRIMARY)");

        Button_Register_CE.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Register_CE.setText("REGISTER");
        Button_Register_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Register_CEActionPerformed(evt);
            }
        });

        Label_CustEntry_CE.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_CustEntry_CE.setText("CUSTOMER ENTRY");

        Button_Back_CE.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Back_CE.setText("BACK");
        Button_Back_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back_CEActionPerformed(evt);
            }
        });

        Button_Login_CE.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Login_CE.setText("LOGIN");
        Button_Login_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Login_CEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Label_Ph_Pri_CE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Button_Back_CE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Button_Register_CE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Button_Login_CE))
                                .addComponent(TextField_Ph_Pri_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(290, 290, 290)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_Logo_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_CustEntry_CE)
                        .addGap(312, 312, 312))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Logo_CE)
                .addGap(41, 41, 41)
                .addComponent(Label_CustEntry_CE)
                .addGap(46, 46, 46)
                .addComponent(Label_Ph_Pri_CE)
                .addGap(38, 38, 38)
                .addComponent(TextField_Ph_Pri_CE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Back_CE)
                    .addComponent(Button_Register_CE)
                    .addComponent(Button_Login_CE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 890, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_Ph_Pri_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Ph_Pri_CEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Ph_Pri_CEActionPerformed

    private void Button_Register_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Register_CEActionPerformed
        Registration r = new Registration();
            r.setVisible(true);
            r.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_Button_Register_CEActionPerformed

    private void Button_Back_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back_CEActionPerformed
        // TODO add your handling code here:
        MainScreen ms = new MainScreen();
            ms.setVisible(true);
            ms.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_Button_Back_CEActionPerformed

    private void Button_Login_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Login_CEActionPerformed
        String phno = this.TextField_Ph_Pri_CE.getText();
        Long l1 = Long.parseLong(phno);
        new FinalCustomer(phno).setVisible(true);
        String phnodb=null; 
        Long l2=null;
        if (phno != null ){
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
                ps = conn.prepareStatement("select Cust_Ph_Primary from Customer where Cust_Ph_Primary = ?");
                ps.setString(1, phno);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    System.out.println(rs.getString("Cust_Ph_Primary"));
                    phnodb = rs.getString("Cust_Ph_Primary");
                     l2 = Long.parseLong(phnodb);
                }
                
                if (phno.equals(phnodb)) {
                    FinalCustomer fs = new FinalCustomer();
            fs.setVisible(true);
            fs.setLocationRelativeTo(null);
            this.dispose();
                    
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Customer Does Not Exist!! Please Check Once Again Or Register.");
                }
            }
            catch(SQLException ex) {
                System.err.println(ex);
            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Login_CEActionPerformed

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back_CE;
    private javax.swing.JButton Button_Login_CE;
    private javax.swing.JButton Button_Register_CE;
    private javax.swing.JLabel Label_CustEntry_CE;
    private javax.swing.JLabel Label_Logo_CE;
    private javax.swing.JLabel Label_Ph_Pri_CE;
    private javax.swing.JTextField TextField_Ph_Pri_CE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
