
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */
public class FinalCustomer extends javax.swing.JFrame {
    String phno1,s1,s2,s3;
    DefaultTableModel model;
    Connection conn;
    PreparedStatement ps;
    int temp;
    /**
     * Creates new form FinalCustomer
     */
    public FinalCustomer (String phno) {
        phno1=phno;
        initComponents();
        this.setPreferredSize(new Dimension(1500, 1500));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("FNAME");
        model.addColumn("MNAME");
        model.addColumn("LNAME");
        model.addColumn("AADHAR");
        model.addColumn("PH. PRI");
        model.addColumn("PH. SEC");
        model.addColumn("EMAIL");
        model.addColumn("ADDRESS");
        model.addColumn("GENDER");
        model.addColumn("MARRIAGE");
        model.addColumn("DOB");
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from Customer where Cust_Ph_Primary = ?");
            ps.setString(1, phno1);
            ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Cust_ID"), rs.getString("Cust_Fname"), rs.getString("Cust_Mname"),rs.getString("Cust_Lname"),rs.getString("Cust_Aadhar"),rs.getString("Cust_Ph_Primary"),rs.getString("Cust_Ph_Secondary"),rs.getString("Cust_Email"),rs.getString("Cust_Address"),rs.getString("Cust_Gender"),rs.getString("Cust_Marriage"),rs.getString("Cust_DOB")});
                }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        Table_CustDets_FC.setModel(model);
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Label_Logo_FC = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Table_CustDets_FC = new javax.swing.JTable();
        Label_Room_Allot_FC = new javax.swing.JLabel();
        Label_ServiceDets_FC = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addidetails = new javax.swing.JTable();
        Label_RoomDets_FC = new javax.swing.JLabel();
        Label_CustDets_FC = new javax.swing.JLabel();
        Label_CheckIN_FC = new javax.swing.JLabel();
        Label_Room_Type_FC = new javax.swing.JLabel();
        Label_Check_Out_FC = new javax.swing.JLabel();
        Label_Nos_Adults_FC = new javax.swing.JLabel();
        ComboBox_Room_Typr_FC = new javax.swing.JComboBox<>();
        TextField_CheckIN_FC = new javax.swing.JTextField();
        TextField_Check_Out_FC = new javax.swing.JTextField();
        TextField_Nos_Adults_FC = new javax.swing.JTextField();
        Label_Nos_Children_FC = new javax.swing.JLabel();
        TextField_Nos_Children_FC = new javax.swing.JTextField();
        Label_Service_Name_FC = new javax.swing.JLabel();
        Label_Service_Rate_FC = new javax.swing.JLabel();
        DEM = new javax.swing.JButton();
        TextField_Service_Name_FC = new javax.swing.JTextField();
        TextField_Service_Rate_FC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Services_Used_FC = new javax.swing.JTable();
        Label_Services_Used_FC = new javax.swing.JLabel();
        TextField_ToPay_FC = new javax.swing.JTextField();
        ComboBox_Via_FC = new javax.swing.JComboBox<>();
        Button_LogOut_FC = new javax.swing.JButton();
        Label_ToPay_FC = new javax.swing.JLabel();
        Label_Via_FC = new javax.swing.JLabel();
        Label_Room_No_FC = new javax.swing.JLabel();
        TextField_Room_No_FC = new javax.swing.JTextField();
        Button_Allot_Room_FC = new javax.swing.JButton();
        Label_Service_Name_FC1 = new javax.swing.JLabel();
        Label_Service_Name_FC2 = new javax.swing.JLabel();
        TextField_Service_Name_FC1 = new javax.swing.JTextField();
        TextField_Service_Name_FC2 = new javax.swing.JTextField();
        Label_RoomDets_FC1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Table_RoomDets_FC1 = new javax.swing.JTable();
        Button_Enter_ServiceDets_FC1 = new javax.swing.JButton();
        DEM2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FNAME", "MNAME", "LNAME", "AADHAR", "PH. PRI", "PH. SEC", "EMAIL", "ADDRESS", "GENDER", "MARRIAGE", "DOB"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CREDIT CARD", "DEBIT CARD", "CHEQUE" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Label_Logo_FC.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_FC.setIcon(new javax.swing.ImageIcon("C:\\Users\\om\\Pictures\\Screenshots\\Screenshot (64).png")); // NOI18N

        Table_CustDets_FC.setBorder(new javax.swing.border.MatteBorder(null));
        Table_CustDets_FC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FNAME", "MNAME", "LNAME", "AADHAR", "PH. PRI", "PH. SEC", "EMAIL", "ADDRESS", "GENDER", "MARRIAGE", "DOB"
            }
        ));
        jScrollPane6.setViewportView(Table_CustDets_FC);

        Label_Room_Allot_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Room_Allot_FC.setText("ROOM ALLOTMENT");

        Label_ServiceDets_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_ServiceDets_FC.setText("SERVICES DETAILS");

        addidetails.setBorder(new javax.swing.border.MatteBorder(null));
        addidetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Room_Type", "Room_Adults", "Room_Children", "Room_CheckOUT", "Room_CheckIN", "Room_Cust_ID", "Room_Cust_Fname", "Room_Cust_Ph_Primary", "Room_No"
            }
        ));
        jScrollPane4.setViewportView(addidetails);

        Label_RoomDets_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_RoomDets_FC.setText("ROOM DETAILS");

        Label_CustDets_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_CustDets_FC.setText("CUSTOMER DETAILS");

        Label_CheckIN_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_CheckIN_FC.setText("CHECK IN DATE");

        Label_Room_Type_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Room_Type_FC.setText("ROOM TYPE");

        Label_Check_Out_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Check_Out_FC.setText("CHECK OUT DATE");

        Label_Nos_Adults_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Nos_Adults_FC.setText("NUMBER OF ADULTS");

        ComboBox_Room_Typr_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        ComboBox_Room_Typr_FC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULAR", "DELUXE", "SUITE" }));

        TextField_CheckIN_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_CheckIN_FCActionPerformed(evt);
            }
        });

        Label_Nos_Children_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Nos_Children_FC.setText("NUMBER OF CHILDREN");

        Label_Service_Name_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Service_Name_FC.setText("SERVICE NAME");

        Label_Service_Rate_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Service_Rate_FC.setText("SERVICE RATE");

        DEM.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        DEM.setText("GO");
        DEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEMActionPerformed(evt);
            }
        });

        TextField_Service_Rate_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Service_Rate_FCActionPerformed(evt);
            }
        });

        Table_Services_Used_FC.setBorder(new javax.swing.border.MatteBorder(null));
        Table_Services_Used_FC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "RATE", "DATE", "TIME"
            }
        ));
        jScrollPane1.setViewportView(Table_Services_Used_FC);

        Label_Services_Used_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Services_Used_FC.setText("SERVICES USED");

        TextField_ToPay_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_ToPay_FCActionPerformed(evt);
            }
        });

        ComboBox_Via_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        ComboBox_Via_FC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CREDIT CARD", "DEBIT CARD", "CHEQUE" }));

        Button_LogOut_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_LogOut_FC.setText("LOG OUT");
        Button_LogOut_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LogOut_FCActionPerformed(evt);
            }
        });

        Label_ToPay_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_ToPay_FC.setText("TO PAY");

        Label_Via_FC.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_Via_FC.setText("VIA");

        Label_Room_No_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Room_No_FC.setText("ROOM NO.");

        Button_Allot_Room_FC.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Allot_Room_FC.setText("ALLOT");
        Button_Allot_Room_FC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Allot_Room_FCActionPerformed(evt);
            }
        });

        Label_Service_Name_FC1.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Service_Name_FC1.setText("SERVICE TIME");

        Label_Service_Name_FC2.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Service_Name_FC2.setText("SERVICE DATE");

        Label_RoomDets_FC1.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_RoomDets_FC1.setText("ADDITIONAL DETAILS");

        Table_RoomDets_FC1.setBorder(new javax.swing.border.MatteBorder(null));
        Table_RoomDets_FC1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ROOM NO.", "TYPE", "STATUS", "RATE"
            }
        ));
        jScrollPane7.setViewportView(Table_RoomDets_FC1);

        Button_Enter_ServiceDets_FC1.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Enter_ServiceDets_FC1.setText("ENTER");
        Button_Enter_ServiceDets_FC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Enter_ServiceDets_FC1ActionPerformed(evt);
            }
        });

        DEM2.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        DEM2.setText("GO");
        DEM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEM2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_ToPay_FC)
                    .addComponent(TextField_ToPay_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Label_Via_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(ComboBox_Via_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Nos_Adults_FC)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_CheckIN_FC)
                                    .addComponent(Label_Room_Type_FC))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextField_CheckIN_FC)
                                    .addComponent(ComboBox_Room_Typr_FC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextField_Nos_Adults_FC))
                                .addGap(126, 126, 126)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Room_No_FC)
                                    .addComponent(Label_Check_Out_FC)
                                    .addComponent(Label_Nos_Children_FC))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_Nos_Children_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_Room_No_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextField_Check_Out_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(366, 366, 366))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Label_Service_Name_FC)
                                        .addGap(23, 23, 23)
                                        .addComponent(TextField_Service_Name_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Label_Service_Rate_FC)
                                        .addGap(29, 29, 29)
                                        .addComponent(TextField_Service_Rate_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(114, 114, 114)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Label_Service_Name_FC1)
                                        .addGap(43, 43, 43)
                                        .addComponent(TextField_Service_Name_FC1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Label_Service_Name_FC2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TextField_Service_Name_FC2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7)
                                    .addComponent(jScrollPane6))))
                        .addComponent(Button_LogOut_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(Label_ServiceDets_FC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(Label_Services_Used_FC)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(552, 552, 552)
                        .addComponent(Label_RoomDets_FC1)
                        .addGap(27, 27, 27)
                        .addComponent(DEM2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(562, 562, 562)
                        .addComponent(Label_Room_Allot_FC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(573, 573, 573)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_RoomDets_FC)
                                .addGap(18, 18, 18)
                                .addComponent(DEM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(Button_Allot_Room_FC)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Logo_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(591, 591, 591)
                .addComponent(Label_CustDets_FC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(623, 623, 623)
                    .addComponent(Button_Enter_ServiceDets_FC1)
                    .addContainerGap(678, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Label_Logo_FC)
                .addGap(27, 27, 27)
                .addComponent(Label_CustDets_FC)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Label_Room_Allot_FC)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Room_Type_FC)
                    .addComponent(ComboBox_Room_Typr_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Room_No_FC)
                    .addComponent(TextField_Room_No_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Nos_Children_FC)
                    .addComponent(TextField_Nos_Adults_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Nos_Adults_FC)
                    .addComponent(TextField_Nos_Children_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Check_Out_FC)
                    .addComponent(TextField_CheckIN_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_CheckIN_FC)
                    .addComponent(TextField_Check_Out_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Allot_Room_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_RoomDets_FC)
                    .addComponent(DEM, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_RoomDets_FC1)
                    .addComponent(DEM2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(Label_ServiceDets_FC)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Service_Name_FC)
                    .addComponent(TextField_Service_Name_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Service_Name_FC2)
                    .addComponent(TextField_Service_Name_FC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Service_Rate_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Service_Rate_FC)
                    .addComponent(Label_Service_Name_FC1)
                    .addComponent(TextField_Service_Name_FC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Services_Used_FC)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label_ToPay_FC)
                                    .addComponent(Label_Via_FC))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextField_ToPay_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComboBox_Via_FC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(Button_LogOut_FC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(155, 155, 155))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(1299, Short.MAX_VALUE)
                    .addComponent(Button_Enter_ServiceDets_FC1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(695, 695, 695)))
        );

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 30, 1260, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEMActionPerformed
        // TODO add your handling code here:
        model = new DefaultTableModel();
        model.addColumn("ROOM NO.");
        model.addColumn("TYPE");
        model.addColumn("STATUS");
        model.addColumn("RATE");
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from Rooms where Room_no=?");
            ps.setInt(1, temp);
            ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Room_No"), rs.getString("Room_Type"), rs.getString("Room_Status"),rs.getString("Room_Rate")});
                }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        Table_RoomDets_FC1.setModel(model);
        
        
    }//GEN-LAST:event_DEMActionPerformed

    private void TextField_Service_Rate_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Service_Rate_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Service_Rate_FCActionPerformed

    private void Button_LogOut_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LogOut_FCActionPerformed
        // TODO add your handling code here:
        CustomerEntry ce = new CustomerEntry();
            ce.setVisible(true);
            ce.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_Button_LogOut_FCActionPerformed

    private void TextField_CheckIN_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_CheckIN_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_CheckIN_FCActionPerformed

    private void Button_Allot_Room_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Allot_Room_FCActionPerformed
        // TODO add your handling code here:
       try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from Customer where Cust_Ph_Primary = ?");
            ps.setString(1, phno1);
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                 s1=rs.getString("Cust_ID");
                 s2=rs.getString("Cust_Fname");
                 s3=rs.getString("Cust_Ph_Primary");
            }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        
        String roomno;
        roomno = this.TextField_Room_No_FC.getText();
        temp=Integer.parseInt(roomno);
        String adults;
        adults = this.TextField_Nos_Adults_FC.getText();
        String children;
        children = this.TextField_Nos_Children_FC.getText();
        String checkin;
        checkin = this.TextField_CheckIN_FC.getText();
        String checkout;
        checkout = this.TextField_Check_Out_FC.getText();
        String roomtype = ComboBox_Room_Typr_FC.getSelectedItem().toString();
        int op=Integer.parseInt(s1);
        try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
                    ps = conn.prepareStatement("insert into RoomAllotment(Room_Type,Room_Adults,Room_Children,Room_CheckOUT,Room_CheckIN,Room_Cust_ID,Room_Cust_Fname,Room_Cust_Ph_Primary,Room_No) values(?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, roomtype);
                    ps.setString(2, adults);
                    ps.setString(3, children);
                    ps.setString(4, checkin);
                    ps.setString(5, checkout);
                    ps.setInt(6, op);
                    ps.setString(7, s2);
                    ps.setString(8, s3);
                    ps.setInt(9, temp);
                    

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Added Successfully");
                    FinalCustomer fe = new FinalCustomer();
                    fe.setVisible(true);
                    fe.setLocationRelativeTo(null);
                    this.dispose();
                }   
                catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Fill All Details");
            
        }
    }//GEN-LAST:event_Button_Allot_Room_FCActionPerformed

    private void TextField_ToPay_FCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ToPay_FCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_ToPay_FCActionPerformed

    private void Button_Enter_ServiceDets_FC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Enter_ServiceDets_FC1ActionPerformed
        // TODO add your handling code here:
        String name;
        name = this.TextField_Service_Name_FC.getText();
        String date;
        date = this.TextField_Service_Name_FC2.getText();
        String rate;
        rate = this.TextField_Service_Rate_FC.getText();
        String time;
        time = this.TextField_Service_Name_FC1.getText();
        
       
        try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
                    ps = conn.prepareStatement("insert into Services(Service_Name,Service_Rate,Service_Date,Service_Time) values(?,?,?,?)");
                    ps.setString(1, name);
                    ps.setString(2, date);
                    ps.setString(3, rate);
                    ps.setString(4, time);
                    
                    

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Added");
                    FinalCustomer fe = new FinalCustomer();
                    fe.setVisible(true);
                    fe.setLocationRelativeTo(null);
                    this.dispose();
                }   
                catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Fill all details");
            
        }
    }//GEN-LAST:event_Button_Enter_ServiceDets_FC1ActionPerformed

    private void DEM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEM2ActionPerformed
        // TODO add your handling code here:
         model = new DefaultTableModel();
        model.addColumn("Room_Type");
        model.addColumn("Room_Adults");
        model.addColumn("Room_Children");
        model.addColumn("Room_CheckOUT");
        model.addColumn("Room_CheckIN");
        model.addColumn("Room_Cust_ID");
        model.addColumn("Room_Cust_Fname");
        model.addColumn("Room_Cust_Ph_Primary");
        model.addColumn("Room_No");
        
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from RoomAllotment where Room_Cust_Ph_Primary=?");
            ps.setString(1, phno1);
            ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Room_Type"),rs.getString("Room_Adults"),rs.getString("Room_Children"),rs.getString("Room_CheckOUT"),rs.getString("Room_CheckIN"),rs.getString("Room_Cust_ID"),rs.getString("Room_Cust_Fname"),rs.getString("Room_Cust_Ph_Primary"),rs.getString("Room_No"),});
                }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        addidetails.setModel(model);
    }//GEN-LAST:event_DEM2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAME");
        model.addColumn("RATE");
        model.addColumn("DATE");
        model.addColumn("TIME");
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
            ps = conn.prepareStatement("select * from Services");
            ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("Service_ID"), rs.getString("Service_Name"),rs.getString("Service_Rate"),rs.getString("Service_Date"),rs.getString("Service_Time")});
                }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        Table_Services_Used_FC.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FinalCustomer().setVisible(true);
                FinalCustomer FinalCustomer = new FinalCustomer("");
                FinalCustomer.setVisible(true);
                FinalCustomer.pack();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Allot_Room_FC;
    private javax.swing.JButton Button_Enter_ServiceDets_FC1;
    private javax.swing.JButton Button_LogOut_FC;
    private javax.swing.JComboBox<String> ComboBox_Room_Typr_FC;
    private javax.swing.JComboBox<String> ComboBox_Via_FC;
    private javax.swing.JButton DEM;
    private javax.swing.JButton DEM2;
    private javax.swing.JLabel Label_CheckIN_FC;
    private javax.swing.JLabel Label_Check_Out_FC;
    private javax.swing.JLabel Label_CustDets_FC;
    private javax.swing.JLabel Label_Logo_FC;
    private javax.swing.JLabel Label_Nos_Adults_FC;
    private javax.swing.JLabel Label_Nos_Children_FC;
    private javax.swing.JLabel Label_RoomDets_FC;
    private javax.swing.JLabel Label_RoomDets_FC1;
    private javax.swing.JLabel Label_Room_Allot_FC;
    private javax.swing.JLabel Label_Room_No_FC;
    private javax.swing.JLabel Label_Room_Type_FC;
    private javax.swing.JLabel Label_ServiceDets_FC;
    private javax.swing.JLabel Label_Service_Name_FC;
    private javax.swing.JLabel Label_Service_Name_FC1;
    private javax.swing.JLabel Label_Service_Name_FC2;
    private javax.swing.JLabel Label_Service_Rate_FC;
    private javax.swing.JLabel Label_Services_Used_FC;
    private javax.swing.JLabel Label_ToPay_FC;
    private javax.swing.JLabel Label_Via_FC;
    private javax.swing.JTable Table_CustDets_FC;
    private javax.swing.JTable Table_RoomDets_FC1;
    private javax.swing.JTable Table_Services_Used_FC;
    private javax.swing.JTextField TextField_CheckIN_FC;
    private javax.swing.JTextField TextField_Check_Out_FC;
    private javax.swing.JTextField TextField_Nos_Adults_FC;
    private javax.swing.JTextField TextField_Nos_Children_FC;
    private javax.swing.JTextField TextField_Room_No_FC;
    private javax.swing.JTextField TextField_Service_Name_FC;
    private javax.swing.JTextField TextField_Service_Name_FC1;
    private javax.swing.JTextField TextField_Service_Name_FC2;
    private javax.swing.JTextField TextField_Service_Rate_FC;
    private javax.swing.JTextField TextField_ToPay_FC;
    private javax.swing.JTable addidetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
