/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        this.setPreferredSize(new Dimension(1500, 1500));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Label_Logo_MS = new javax.swing.JLabel();
        Button_RoomDets_MS = new javax.swing.JButton();
        Button_CustEntry_MS = new javax.swing.JButton();
        Label_MainScreen_MS = new javax.swing.JLabel();
        Button_Back_MS = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        jLabel7.setText("ADMIN LOGIN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Label_Logo_MS.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_MS.setIcon(new javax.swing.ImageIcon("C:\\Users\\om\\Pictures\\Screenshots\\Screenshot (64).png")); // NOI18N

        Button_RoomDets_MS.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_RoomDets_MS.setText("ROOM DETAILS");
        Button_RoomDets_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RoomDets_MSActionPerformed(evt);
            }
        });

        Button_CustEntry_MS.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_CustEntry_MS.setText("CUSTOMER ENTRY");
        Button_CustEntry_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CustEntry_MSActionPerformed(evt);
            }
        });

        Label_MainScreen_MS.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_MainScreen_MS.setText("MAIN SCREEN");

        Button_Back_MS.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Back_MS.setText("BACK");
        Button_Back_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back_MSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(Button_RoomDets_MS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_CustEntry_MS)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_Logo_MS)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_MainScreen_MS)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_Back_MS)
                                .addGap(33, 33, 33)))
                        .addGap(291, 291, 291))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Label_Logo_MS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_MainScreen_MS)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_RoomDets_MS)
                    .addComponent(Button_CustEntry_MS))
                .addGap(37, 37, 37)
                .addComponent(Button_Back_MS)
                .addGap(41, 41, 41))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 10, 660, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_RoomDets_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RoomDets_MSActionPerformed

         RoomDetails rd = new RoomDetails();
            rd.setVisible(true);
            rd.setLocationRelativeTo(null);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_RoomDets_MSActionPerformed

    private void Button_CustEntry_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CustEntry_MSActionPerformed

        CustomerEntry ce = new CustomerEntry();
            ce.setVisible(true);
            ce.setLocationRelativeTo(null);
            this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_CustEntry_MSActionPerformed

    private void Button_Back_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back_MSActionPerformed
        // TODO add your handling code here:
        EmployeeLogin el = new EmployeeLogin();
            el.setVisible(true);
            el.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_Button_Back_MSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back_MS;
    private javax.swing.JButton Button_CustEntry_MS;
    private javax.swing.JButton Button_RoomDets_MS;
    private javax.swing.JLabel Label_Logo_MS;
    private javax.swing.JLabel Label_MainScreen_MS;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
