

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rushikeshgadewar
 */

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

        
public class Registration extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps; 
    
    /**
     * Creates new form Rushi1
     */
    String gender1,marriage1;
    public Registration() {
        initComponents();
        this.setPreferredSize(new Dimension(1500, 1500));
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        groupRadio();
        
    }
    public void groupRadio(){
        
        genderGroup.add(MaleRadio);
        genderGroup.add(FemaleRadio);

    }
    public void groupradio(){
        marriageGroup.add(YesRadio);
        marriageGroup.add(NoRadio);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        marriageGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Cust_Fname = new javax.swing.JTextField();
        Label_Name_NCR = new javax.swing.JLabel();
        Label_Logo_NCR = new javax.swing.JLabel();
        Label_NCR = new javax.swing.JLabel();
        Cust_Mname = new javax.swing.JTextField();
        Cust_Lname = new javax.swing.JTextField();
        Label_Fname_NCR = new javax.swing.JLabel();
        Label_Mname_NCR = new javax.swing.JLabel();
        Label_Lname_NCR = new javax.swing.JLabel();
        Label_Ph_Pri_NCR = new javax.swing.JLabel();
        Cust_Ph_Primary = new javax.swing.JTextField();
        Cust_Email = new javax.swing.JTextField();
        Label_Ph_Sec_NCR = new javax.swing.JLabel();
        Label_Email_NCR = new javax.swing.JLabel();
        Cust_Ph_Secondary = new javax.swing.JTextField();
        Label_Aadhar_NCR = new javax.swing.JLabel();
        Cust_Aadhar = new javax.swing.JTextField();
        Label_DOB_NCR = new javax.swing.JLabel();
        Cust_DOB = new javax.swing.JTextField();
        Label_Marr_Status_NCR = new javax.swing.JLabel();
        YesRadio = new javax.swing.JRadioButton();
        NoRadio = new javax.swing.JRadioButton();
        Label_Gender_NCR = new javax.swing.JLabel();
        MaleRadio = new javax.swing.JRadioButton();
        FemaleRadio = new javax.swing.JRadioButton();
        Button_Register_NCR = new javax.swing.JButton();
        Button_Back_NCR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Cust_Address = new javax.swing.JTextArea();
        Label_DOB_NCR1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Cust_Fname.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        Cust_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_FnameActionPerformed(evt);
            }
        });

        Label_Name_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Name_NCR.setText("NAME");

        Label_Logo_NCR.setFont(new java.awt.Font("Zapfino", 1, 36)); // NOI18N
        Label_Logo_NCR.setIcon(new javax.swing.ImageIcon("C:\\Users\\om\\Pictures\\Screenshots\\Screenshot (64).png")); // NOI18N

        Label_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        Label_NCR.setText("NEW CUSTOMER REGISTRATION");

        Cust_Mname.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N

        Cust_Lname.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        Cust_Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_LnameActionPerformed(evt);
            }
        });

        Label_Fname_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Fname_NCR.setText("FIRST");

        Label_Mname_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Mname_NCR.setText("MIDDLE");

        Label_Lname_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Lname_NCR.setText("LAST");

        Label_Ph_Pri_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Ph_Pri_NCR.setText("PHONE NO.(PRIMARY)");

        Cust_Ph_Primary.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        Cust_Ph_Primary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_Ph_PrimaryActionPerformed(evt);
            }
        });

        Cust_Email.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        Cust_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_EmailActionPerformed(evt);
            }
        });

        Label_Ph_Sec_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Ph_Sec_NCR.setText("PHONE NO.(SECONDARY)");

        Label_Email_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Email_NCR.setText("EMAIL ID");

        Cust_Ph_Secondary.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        Cust_Ph_Secondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_Ph_SecondaryActionPerformed(evt);
            }
        });

        Label_Aadhar_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Aadhar_NCR.setText("AADHAR NUMBER");

        Cust_Aadhar.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        Cust_Aadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_AadharActionPerformed(evt);
            }
        });

        Label_DOB_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_DOB_NCR.setText("DATE OF BIRTH");

        Cust_DOB.setFont(new java.awt.Font("STIX Two Text", 0, 14)); // NOI18N
        Cust_DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_DOBActionPerformed(evt);
            }
        });

        Label_Marr_Status_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Marr_Status_NCR.setText("MARRIAGE STATUS");

        marriageGroup.add(YesRadio);
        YesRadio.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        YesRadio.setText("YES");
        YesRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YesRadioMouseClicked(evt);
            }
        });
        YesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesRadioActionPerformed(evt);
            }
        });

        marriageGroup.add(NoRadio);
        NoRadio.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        NoRadio.setText("NO");
        NoRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoRadioMouseClicked(evt);
            }
        });
        NoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRadioActionPerformed(evt);
            }
        });

        Label_Gender_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_Gender_NCR.setText("GENDER");

        genderGroup.add(MaleRadio);
        MaleRadio.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        MaleRadio.setText("MALE");
        MaleRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaleRadioMouseClicked(evt);
            }
        });
        MaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioActionPerformed(evt);
            }
        });

        genderGroup.add(FemaleRadio);
        FemaleRadio.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        FemaleRadio.setText("FEMALE");
        FemaleRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FemaleRadioMouseClicked(evt);
            }
        });
        FemaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioActionPerformed(evt);
            }
        });

        Button_Register_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Register_NCR.setText("REGISTER");
        Button_Register_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Register_NCRActionPerformed(evt);
            }
        });

        Button_Back_NCR.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Button_Back_NCR.setText("BACK");
        Button_Back_NCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back_NCRActionPerformed(evt);
            }
        });

        Cust_Address.setColumns(20);
        Cust_Address.setRows(5);
        jScrollPane2.setViewportView(Cust_Address);

        Label_DOB_NCR1.setFont(new java.awt.Font("STIX Two Text", 1, 14)); // NOI18N
        Label_DOB_NCR1.setText("ADDRESS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Ph_Sec_NCR)
                    .addComponent(Label_DOB_NCR)
                    .addComponent(Cust_Aadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Aadhar_NCR)
                    .addComponent(Cust_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Email_NCR)
                    .addComponent(Cust_Ph_Secondary, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cust_Ph_Primary, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Ph_Pri_NCR)
                    .addComponent(Label_Name_NCR)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Label_Fname_NCR)
                        .addGap(62, 62, 62)
                        .addComponent(Label_Mname_NCR)
                        .addGap(58, 58, 58)
                        .addComponent(Label_Lname_NCR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cust_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cust_Mname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cust_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_DOB_NCR1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Button_Back_NCR)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Register_NCR))
                        .addComponent(Cust_DOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_Marr_Status_NCR)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(YesRadio)
                            .addGap(31, 31, 31)
                            .addComponent(NoRadio))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_Gender_NCR)
                            .addGap(36, 36, 36)
                            .addComponent(MaleRadio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FemaleRadio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_Logo_NCR)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_NCR)
                        .addGap(291, 291, 291))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Logo_NCR)
                .addGap(37, 37, 37)
                .addComponent(Label_NCR)
                .addGap(42, 42, 42)
                .addComponent(Label_Name_NCR)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cust_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cust_Mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cust_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Fname_NCR)
                    .addComponent(Label_Mname_NCR)
                    .addComponent(Label_Lname_NCR))
                .addGap(24, 24, 24)
                .addComponent(Label_Ph_Pri_NCR)
                .addGap(18, 18, 18)
                .addComponent(Cust_Ph_Primary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(Label_Ph_Sec_NCR)
                .addGap(18, 18, 18)
                .addComponent(Cust_Ph_Secondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Email_NCR)
                .addGap(18, 18, 18)
                .addComponent(Cust_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_Aadhar_NCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cust_Aadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_DOB_NCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cust_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Label_DOB_NCR1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Gender_NCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaleRadio)
                    .addComponent(FemaleRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Marr_Status_NCR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YesRadio)
                    .addComponent(NoRadio))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Back_NCR)
                    .addComponent(Button_Register_NCR))
                .addGap(236, 236, 236))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 960, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cust_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_FnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Cust_FnameActionPerformed

    private void Cust_LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_LnameActionPerformed

    private void Cust_Ph_PrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_Ph_PrimaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_Ph_PrimaryActionPerformed

    private void Cust_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_EmailActionPerformed

    private void Cust_Ph_SecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_Ph_SecondaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_Ph_SecondaryActionPerformed

    private void Cust_DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_DOBActionPerformed

    private void Cust_AadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_AadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cust_AadharActionPerformed

    private void FemaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioActionPerformed
        // TODO add your handling code here:
        gender1= FemaleRadio.getText();
    }//GEN-LAST:event_FemaleRadioActionPerformed

    private void NoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRadioActionPerformed
        // TODO add your handling code here:
        marriage1= NoRadio.getText();
    }//GEN-LAST:event_NoRadioActionPerformed

    private void Button_Register_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Register_NCRActionPerformed
        // TODO add your handling code here:
        String fname;
        fname = this.Cust_Fname.getText();
        String mname;
        mname = this.Cust_Mname.getText();
        String lname;
        lname = this.Cust_Lname.getText();
        String phnopri;
        phnopri = this.Cust_Ph_Primary.getText();
        String phnosec;
        phnosec = this.Cust_Ph_Secondary.getText();
        String email;
        email = this.Cust_Email.getText();
        String aadhar;
        aadhar = this.Cust_Aadhar.getText();
        String dob;
        dob = this.Cust_DOB.getText();
        String address;
        address = this.Cust_Address.getText();
        try {
                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel Management?user=root&password=Rushi12345$");
                    ps = conn.prepareStatement("insert into Customer(Cust_Fname,Cust_Mname,Cust_Lname,Cust_Ph_Primary,Cust_Ph_Secondary,Cust_Email,Cust_Aadhar,Cust_DOB,Cust_Address,Cust_Gender,Cust_Marriage) values(?,?,?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, fname);
                    ps.setString(2, mname);
                    ps.setString(3, lname);
                    ps.setString(4, phnopri);
                    ps.setString(5, phnosec);
                    ps.setString(6, email);
                    ps.setString(7, aadhar);
                    ps.setString(8, dob);
                    ps.setString(9, address);
                    ps.setString(10, gender1);
                    ps.setString(11, marriage1);

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Added");
                    CustomerEntry ce = new CustomerEntry();
                    ce.setVisible(true);
                    ce.setLocationRelativeTo(null);
                    this.dispose();
                }   
                catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Fill all details");
            
        }
    }//GEN-LAST:event_Button_Register_NCRActionPerformed

    private void Button_Back_NCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back_NCRActionPerformed
        // TODO add your handling code here:
         CustomerEntry ce = new CustomerEntry();
            ce.setVisible(true);
            ce.setLocationRelativeTo(null);
            this.dispose();

    }//GEN-LAST:event_Button_Back_NCRActionPerformed

    private void MaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioActionPerformed
        // TODO add your handling code here:
        gender1= MaleRadio.getText();
    }//GEN-LAST:event_MaleRadioActionPerformed

    private void YesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesRadioActionPerformed
        // TODO add your handling code here:
        marriage1= YesRadio.getText();
    }//GEN-LAST:event_YesRadioActionPerformed

    private void YesRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesRadioMouseClicked
        // TODO add your handling code here:
        marriage= "Yes";
    }//GEN-LAST:event_YesRadioMouseClicked

    private void NoRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoRadioMouseClicked
        // TODO add your handling code here:
        marriage= "No";
    }//GEN-LAST:event_NoRadioMouseClicked

    private void MaleRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaleRadioMouseClicked
        // TODO add your handling code here:
        gender = "Male";
    }//GEN-LAST:event_MaleRadioMouseClicked

    private void FemaleRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FemaleRadioMouseClicked
        // TODO add your handling code here:
        gender = "Female";
    }//GEN-LAST:event_FemaleRadioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back_NCR;
    private javax.swing.JButton Button_Register_NCR;
    private javax.swing.JTextField Cust_Aadhar;
    private javax.swing.JTextArea Cust_Address;
    private javax.swing.JTextField Cust_DOB;
    private javax.swing.JTextField Cust_Email;
    private javax.swing.JTextField Cust_Fname;
    private javax.swing.JTextField Cust_Lname;
    private javax.swing.JTextField Cust_Mname;
    private javax.swing.JTextField Cust_Ph_Primary;
    private javax.swing.JTextField Cust_Ph_Secondary;
    private javax.swing.JRadioButton FemaleRadio;
    private javax.swing.JLabel Label_Aadhar_NCR;
    private javax.swing.JLabel Label_DOB_NCR;
    private javax.swing.JLabel Label_DOB_NCR1;
    private javax.swing.JLabel Label_Email_NCR;
    private javax.swing.JLabel Label_Fname_NCR;
    private javax.swing.JLabel Label_Gender_NCR;
    private javax.swing.JLabel Label_Lname_NCR;
    private javax.swing.JLabel Label_Logo_NCR;
    private javax.swing.JLabel Label_Marr_Status_NCR;
    private javax.swing.JLabel Label_Mname_NCR;
    private javax.swing.JLabel Label_NCR;
    private javax.swing.JLabel Label_Name_NCR;
    private javax.swing.JLabel Label_Ph_Pri_NCR;
    private javax.swing.JLabel Label_Ph_Sec_NCR;
    private javax.swing.JRadioButton MaleRadio;
    private javax.swing.JRadioButton NoRadio;
    private javax.swing.JRadioButton YesRadio;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup marriageGroup;
    // End of variables declaration//GEN-END:variables
    private String gender;
    private String marriage;
    
    private String getText111() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
